version: '3.8'

services:
  # フロントエンド
  frontend:
    build:
      context: ../../..
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api
    restart: unless-stopped

  # バックエンドAPI
  api:
    build:
      context: ../../..
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    volumes:
      # ログファイルを永続化
      - ~/.claude:/root/.claude
      - ~/.gemini:/root/.gemini
      - ~/.cursor:/root/.cursor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
