name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          cache: 'npm'

      - name: Install dependencies (workspace aware)
        run: |
          npm install
          npm install --prefix packages/sdk
          npm install --prefix packages/cli
          npm install --prefix backend
          npm install --prefix frontend

      - name: Backend checks
        run: npm run backend:check

      - name: Frontend checks
        run: npm run frontend:check

      - name: Build SDK artifacts
        run: npm run build --workspace packages/sdk

      - name: Build application bundles
        run: npm run build

      - name: Build CLI runtime
        run: npm run build:cli

      - name: Verify exports paths exist
        run: |
          echo "Checking if all exported files exist..."
          
          echo "# Checking CLI export targets"
          cd packages/cli
          CLI_EXPORTS=(
            "dist/runtime/backend/dist/index.js"
            "dist/runtime/backend/dist/services/src/execution/index.js"
            "dist/runtime/backend/dist/services/src/logs/index.js"
            "dist/runtime/backend/dist/server/src/routes/index.js"
            "dist/runtime/backend/dist/utils/src/logger.js"
          )
          MISSING=0
          for file in "${CLI_EXPORTS[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing CLI artifact: $file"
              MISSING=$((MISSING + 1))
            else
              echo "✅ Found CLI artifact: $file"
            fi
          done
          if [ $MISSING -gt 0 ]; then
            exit 1
          fi

          echo "# Checking SDK export targets"
          cd ../sdk
          SDK_EXPORTS=(
            "dist/esm/index.js"
            "dist/cjs/index.js"
            "dist/types/index.d.ts"
            "dist/esm/services/logs/index.js"
            "dist/esm/services/execution/index.js"
            "dist/esm/server/routes/index.js"
            "dist/esm/utils/logger.js"
          )
          MISSING=0
          for file in "${SDK_EXPORTS[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing SDK artifact: $file"
              MISSING=$((MISSING + 1))
            else
              echo "✅ Found SDK artifact: $file"
            fi
          done
          if [ $MISSING -gt 0 ]; then
            exit 1
          fi
