name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install workspace dependencies
        run: npm run install:all

      - name: Backend checks
        run: npm run backend:check

      - name: Frontend checks
        run: npm run frontend:check

      - name: Build application bundles
        run: npm run build

      - name: Build NPX package assets
        run: npm run build:npx

      - name: Verify exports paths exist
        run: |
          echo "Checking if all exported files exist..."
          cd npx-cli
          
          EXPORTS=(
            "dist/runtime/backend/dist/services/src/execution/index.js"
            "dist/runtime/backend/dist/services/src/execution/executionService.js"
            "dist/runtime/backend/dist/services/src/execution/activeExecutionRegistry.js"
            "dist/runtime/backend/dist/services/src/logs/index.js"
            "dist/runtime/backend/dist/services/src/logs/logSourceFactory.js"
            "dist/runtime/backend/dist/server/src/routes/index.js"
            "dist/runtime/backend/dist/server/src/middleware/errorHandler.js"
            "dist/runtime/backend/dist/utils/src/logger.js"
          )
          
          MISSING=0
          for file in "${EXPORTS[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              MISSING=$((MISSING + 1))
            else
              echo "✅ Found: $file"
            fi
          done
          
          if [ $MISSING -gt 0 ]; then
            echo "Error: $MISSING file(s) missing from exports"
            exit 1
          fi
          
          echo "All exported files exist!"
